export const styles = {
  header: {
    backgroundColor: '#1f1f1f',
    fontFamily: 'Overlock',
    color: '#fff',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    height: 70,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -20 },
    shadowOpacity: 1,
    shadowRadius: 45,
    elevation: 8,
    zIndex: 1000,
    gap: 10,
  } as unknown,
  headerBrand: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 25,
  } as unknown,
  headerImage: {
    width: 65,
    height: 65,
  } as unknown,
  headerTitle: {
    fontFamily: 'Overlock',
    fontSize: 'clamp(1.5rem, 5vw, 2.5rem)',
    fontWeight: '400',
    color: '#D2C682',
  } as unknown,
  screenTitle: {
    fontFamily: 'Overlock',
    fontSize: 28,
    color: '#D2C682',
    padding: 10,
    borderBottomWidth: 3,
    borderBottomColor: '#D2C682',
    width: '80%',
    textAlign: 'center',
  } as unknown,
  main: {
    display: 'flex',
    backgroundColor: '#181815',
    minHeight: '100%',
    alignItems: 'center',
  } as unknown,
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  } as unknown,
  twoColitemsList: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    width: '100%',
    columnGap: 20,
  } as unknown,
  oneColitemsList: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    width: '100%',
  } as unknown,
  itemContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: '#EED3',
    minHeight: 85,
    gap: 10,
  } as unknown,
  itemController: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  } as unknown,
  itemQuantityInput: {
    fontSize: 'clamp(0.7rem, 1vw, 1rem)',
    textAlign: 'center',
    width: 22,
    height: 22,
    backgroundColor: '#f5f5dc',
    borderRadius: 5,
    fontWeight: 'bold',
    color: '#1f1f1f',
  } as unknown,
  itemImage: {
    width: 65,
    height: 65,
    borderRadius: 5,
  } as unknown,
  itemInfo: {
    display: 'flex',
    flexDirection: 'column',
    flexShrink: 1,
    maxHeight: '100%',
    overflowY: 'auto',
    flexBasis: 100000,
  } as unknown,
  itemName: {
    fontSize: 'clamp(1rem, 3vw, 1.5rem)',
    // fontWeight: 'bold',
    fontFamily: 'Overlock',
    color: '#F5F5DC',
  } as unknown,
  itemDescription: {
    fontSize: 'clamp(0.8rem, 2vw, 1rem)',
    fontFamily: 'Overlock',
    color: '#F5F5DC',
  } as unknown,
  itemPriceAndController: {
    flexBasis: 50,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'end',
  } as unknown,
  itemPrice: {
    marginRight: 5,
    fontSize: 'clamp(1rem, 3vw, 1.5rem)',
    fontWeight: 'bold',
    fontFamily: 'Overlock',
    color: '#F5F5DC',
  } as unknown,
  itemQuantityControllerContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  } as unknown,
  itemQuantityController: {
    width: 22,
    height: 22,
    fontWeight: 'bold',
    fontFamily: 'Overlock',
    backgroundColor: '#181815',
  } as unknown,
  title: {
    fontFamily: 'Overlock',
    fontSize: 'clamp(1.5rem, 5vw, 2.5rem)',
    fontWeight: 'bold',
  } as unknown,
  separator: {
    marginVertical: 30,
    height: 1,
    width: '80%',
  } as unknown,
}
