const adminStyles = {
  table: {
    width: '100%',
  },
  tableText: {
    flexWrap: 'wrap',
    color: '#F5F5DC',
    textAlign: 'center',
    width: '100%',
    fontFamily: 'Overlock',
    fontSize: 12,
    paddingVertical: 5,
  },
  tableHeaderText: {
    color: '#D2C682',
    textAlign: 'center',
    width: '100%',
    fontFamily: 'Overlock',
    fontSize: 16,
  },
  tableImage: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
  },
  twoColumns: {
    display: 'grid',
    width: '90%',
    gap: 20,
    gridTemplateColumns: '4fr 1fr',
  },
  oneColumn: {
    display: 'flex',
    flexDirection: 'column',
    width: '90%',
    gap: 20,
    justifyContent: 'center',
  },
  selectBox: {
    borderWidth: 0,
    width: '100%',
    paddingVertical: 9,
    height: 40,
    paddingHorizontal: 15,
    borderRadius: 5,
    backgroundColor: '#EED3',
  },
  selectInput: {
    color: '#F5F5DC',
    fontFamily: 'Overlock',
    fontSize: 16,
  },
  input: {
    width: '100%',
    height: 40,
    color: '#F5F5DC',
    fontFamily: 'Overlock',
    fontSize: 16,
    paddingHorizontal: 15,
    borderRadius: 5,
    backgroundColor: '#EED3',
  },
  selectedRow: {
    backgroundColor: '#DC83',
    borderBottomColor: '#EED3',
  },
  actions: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'start',
    gap: 20,
    width: '100%',
  },
  activeActionButton: {
    width: '100%',
    maxWidth: 500,
    padding: 10,
    borderRadius: 5,
    backgroundColor: '#D2C682',
    transition: 'background-color 0.3s ease-out',
  },
  activeActionButtonText: {
    color: '#181815',
    fontFamily: 'OverlockBlack',
    fontSize: 16,
    textAlign: 'center',
  },
  dangerActionButton: {
    width: '100%',
    maxWidth: 500,
    padding: 10,
    borderRadius: 5,
    backgroundColor: '#9F1A1A',
  },
  dangerActionButtonText: {
    color: '#F5F5DC',
    fontFamily: 'Overlock',
    fontSize: 16,
    textAlign: 'center',
  },
  actionButton: {
    width: '100%',
    maxWidth: 500,
    padding: 10,
    borderRadius: 5,
    backgroundColor: '#F5F5DC',
    transition: 'background-color 1s ease-out',
  },
  actionButtonText: {
    color: '#181815',
    fontFamily: 'Overlock',
    fontSize: 16,
    textAlign: 'center',
  },
  modal: {
    width: '80%',
    marginLeft: '10%',
  },
  modalContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    gap: 20,
    backgroundColor: '#181815',
    borderRadius: 5,
  },
  modalText: {
    color: '#F5F5DC',
    fontFamily: 'Overlock',
    fontSize: 16,
    textAlign: 'center',
  },
  loadingPortal: {
    height: '100%',
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
}

export default adminStyles
